version: '3.7'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

services:
  auth-dev:
    volumes:
      - ./auth:/app
    build:
      context: .
      dockerfile: Dockerfile_auth
      target: development
      args:
        <<: *build_args
    image: auth:dev
    container_name: auth-dev
    ports:
      - 127.0.0.1:80:5000/tcp
      - 4444:4444 # for debugging
    env_file:
      - auth/environments/env_dev.txt
    restart: always
    stdin_open: true # for debugging
    tty: true # for debugging


  products-reverse-proxy-dev:
    volumes:
      - ./reverse_proxy:/app
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile_reverse_proxy
      target: development
      args:
        <<: *build_args
    image: reverse-proxy:dev
    container_name: products-reverse-proxy-dev
    ports:
      - 127.0.0.1:1001:5000/tcp
      - 4401:4444 # for debugging
    env_file:
      - reverse_proxy/environments/env_dev.txt
    restart: always
    stdin_open: true # for debugging
    tty: true # for debugging
    environment:
      - API_HOST=products-api-dev:5000
      - URL_HOST=0.0.0.0:1001


  orders-reverse-proxy-dev:
    volumes:
      - ./reverse_proxy:/app
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile_reverse_proxy
      target: development
      args:
        <<: *build_args
    image: reverse-proxy:dev
    container_name: orders-reverse-proxy-dev
    ports:
      - 127.0.0.1:1002:5000/tcp
      - 4402:4444 # for debugging
    env_file:
      - reverse_proxy/environments/env_dev.txt
    restart: always
    stdin_open: true # for debugging
    tty: true # for debugging
    environment:
      - API_HOST=orders-api-dev:5000
      - URL_HOST=0.0.0.0:1002


  products-api-dev:
    volumes:
      - ./api:/app
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile_api
      target: development
      args:
        <<: *build_args
    image: api:dev
    container_name: products-api-dev
    ports:
      - 127.0.0.1:2001:5000/tcp
      - 4411:4444 # for debugging
    env_file:
      - api/environments/env_dev.txt
    restart: always
    stdin_open: true # for debugging
    tty: true # for debugging
    environment:
      - URL_HOST=products-api-dev:5000


  orders-api-dev:
    volumes:
      - ./api:/app
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile_api
      target: development
      args:
        <<: *build_args
    image: api:dev
    container_name: orders-api-dev
    ports:
      - 127.0.0.1:2002:5000/tcp
      - 4422:4444 # for debugging
    env_file:
      - api/environments/env_dev.txt
    restart: always
    stdin_open: true # for debugging
    tty: true # for debugging
    environment:
      - URL_HOST=0.0.0.0:2002


  oauth2-token-db-dev:
    image: postgres:10
    networks:
      - internal
    container_name: oauth2-token-db-dev
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./oauth2-token-db-dev.postgresdb:/var/lib/postgresql/data
    env_file:
      - auth/environments/env_dev_db.txt


  oauth2-token-db-test:
    image: postgres:10
    networks:
      - internal
    container_name: oauth2-token-db-test
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./oauth2-token-db-test.postgresdb:/var/lib/postgresql/data
    env_file:
      - auth/environments/env_test_db.txt

networks:
  internal:
