version: '3.7'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.7
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app

services:
  reverse-proxy-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: reverse-proxy:dev
    container_name: reverse-proxy-dev
    ports:
      - 127.0.0.1:81:5000/tcp
      - 4445:4444 # for debugging
    <<: *default_volumes
    env_file:
      - environments/env_dev.txt
    stdin_open: true # for debugging
    tty: true # for debugging
