"""empty message

Revision ID: a003a3d35e56
Revises: f18544a62436
Create Date: 2022-01-26 15:46:09.424541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a003a3d35e56'
down_revision = 'f18544a62436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    partners_table = op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('secret_key', sa.String(length=256), nullable=True),
    sa.Column('scopes', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('oauth2_tokens', sa.Column('partner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_oauth2_tokens_partner_id'), 'oauth2_tokens', ['partner_id'], unique=False)
    op.create_foreign_key('ix_oauth2_tokens_partners', 'oauth2_tokens', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###

    op.bulk_insert(partners_table,
    [
        {   'id':1,
            'name': 'tokopedia',
            'secret_key':'XYZ',
            'scopes':
                {
                    '/api/v1/lists': ['GET'],
                    '/api/v1/detail/<id>': ['GET'],
                    '/api/v1/add_to_cart': ['POST'],
                    '/api/v1/cart/detail/<id>': ['GET'],
                    '/api/v1/cart/checkout': ['POST']
                }
        },
        {   'id':2,
            'name': 'shopee',
            'secret_key':'QQQ',
            'scopes':
                {
                    '/api/v1/lists': ['GET'],
                    '/api/v1/detail/<id>': ['GET']
                }
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_oauth2_tokens_partners', 'oauth2_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_oauth2_tokens_partner_id'), table_name='oauth2_tokens')
    op.drop_column('oauth2_tokens', 'partner_id')
    op.drop_table('partners')
    # ### end Alembic commands ###
