"""empty message

Revision ID: f18544a62436
Revises: cdfbef659b69
Create Date: 2022-01-26 11:53:05.795546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18544a62436'
down_revision = 'cdfbef659b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=True),
    sa.Column('token_type', sa.String(length=40), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('issued_at', sa.Integer(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_code', sa.String(length=256), nullable=True),
    sa.Column('scopes', sa.JSON(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_oauth2_tokens_refresh_token'), 'oauth2_tokens', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_oauth2_tokens_user_id'), 'oauth2_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2_tokens_user_id'), table_name='oauth2_tokens')
    op.drop_index(op.f('ix_oauth2_tokens_refresh_token'), table_name='oauth2_tokens')
    op.drop_table('oauth2_tokens')
    # ### end Alembic commands ###
